name: Push Check

on: [push]

jobs:
  say-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Say Success
        run: echo "✅ Push was successful!"
